version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sumeet_sit722_part5_user
      POSTGRES_PASSWORD: zJpzgbmSyVe89lFPL0ZSguYtxVeMdpQH
      POSTGRES_DB: sumeet_sit722_part5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book_catalog:
    build: ./book_catalog
    image: sit722part5.azurecr.io/book_catalog:latest
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "postgresql://sumeet_sit722_part5_user:zJpzgbmSyVe89lFPL0ZSguYtxVeMdpQH@dpg-croq23dumphs739bs30g-a.oregon-postgres.render.com:5432/sumeet_sit722_part5?sslmode=require"
    depends_on:
      - postgres

  inventory_management:
    build: ./inventory_management
    image: sit722part5.azurecr.io/inventory_management:latest
    ports:
      - "8001:80"
    environment:
      DATABASE_URL: "postgresql://sumeet_sit722_part5_user:zJpzgbmSyVe89lFPL0ZSguYtxVeMdpQH@dpg-croq23dumphs739bs30g-a.oregon-postgres.render.com:5432/sumeet_sit722_part5?sslmode=require"
    depends_on:
      - postgres

volumes:
  postgres_data:
