name: CI/CD Pipeline for Cloud-Native DevOps Project

on:
  push:
    branches:
      - main   # Trigger the workflow when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository (use Node 16+ compatible version)
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform (use Node 16+ compatible version)
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Initialize Terraform
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # Step 4: Apply Terraform to provision Azure resources
    - name: Terraform Apply
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform apply -auto-approve

    # Step 5: Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72

    # Step 6: Log in to Azure and retrieve AKS credentials
    - name: Log in to Azure and Set AKS Credentials
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.KUBERNETES_CLUSTER_NAME }}

    # Step 7: Build and push Docker images for both microservices
    - name: Build and Push Docker Images
      run: |
        ./scripts/build-image.sh
        ./scripts/push-image.sh

    # Step 8: Deploy to AKS using kubectl
    - name: Deploy to AKS
      run: ./scripts/deploy.sh

    # Optional Step: Verify deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
