name: CI/CD Pipeline for Cloud-Native DevOps Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Initialize Terraform
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # Step 4: Apply Terraform to provision Azure resources
    - name: Terraform Apply
      working-directory: ./terraform
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -var "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" -var "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" -auto-approve

    # Step 5: Set up Azure CLI and Fetch AKS Credentials
    - name: Set up Azure CLI and Fetch AKS Credentials
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.KUBERNETES_CLUSTER_NAME }}
      shell: bash
    # Step 6: Build and push Docker images for both microservices
    - name: Build and Push Docker Images
      run: |
        chmod +x ./scripts/build-image.sh
        chmod +x ./scripts/push-image.sh
        ./scripts/build-image.sh
        ./scripts/push-image.sh

    # Step 7: Deploy to AKS using kubectl
    - name: Deploy to AKS
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh

    # Optional Step: Verify deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
